### ISSUE TITLE
unable to start jenkins though I have required config file under /var/jenkins_home/casc_configs

### ISSUE THREAD

**Issue by ycx356** [Praqma/jenkins4casc#6]
Aug 22, 2019 1:43:41 AM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
WARNING: Failed to load io.jenkins.plugins.casc.support.credentials.DirectEntryPrivateKeySourceConfigurator
java.lang.LinkageError: Failed to resolve class io.jenkins.plugins.casc.support.credentials.DirectEntryPrivateKeySourceConfigurator
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:507)
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:527)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:285)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
        at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:715)
        at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:690)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:494)
        at hudson.ExtensionList.load(ExtensionList.java:380)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:318)
        at hudson.ExtensionList.getComponents(ExtensionList.java:183)
        at jenkins.model.Jenkins$6.onInitMilestoneAttained(Jenkins.java:1114)
        at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:83)
        at org.jvnet.hudson.reactor.ReactorListener$Aggregator.lambda$onAttained$3(ReactorListener.java:102)
        at org.jvnet.hudson.reactor.ReactorListener$Aggregator.run(ReactorListener.java:109)
        at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:102)
        at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:177)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.TypeNotPresentException: Type com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource not present
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
        at java.lang.Class.getGenericSuperclass(Class.java:777)
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:488)
        ... 31 more
Caused by: java.lang.ClassNotFoundException: com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1327)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1080)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
        ... 39 more

Aug 22, 2019 1:43:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
Aug 22, 2019 1:43:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
Aug 22, 2019 1:43:41 AM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
Aug 22, 2019 1:43:41 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed ConfigurationAsCode.init
java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1083)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        ... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration: '/var/jenkins_home/casc_configs/jenkins.yaml' isn't a valid path.
        at io.jenkins.plugins.casc.ConfigurationAsCode.configs(ConfigurationAsCode.java:572)
        at io.jenkins.plugins.casc.ConfigurationAsCode.getStandardConfigSources(ConfigurationAsCode.java:285)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
        at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
        ... 13 more

Aug 22, 2019 1:43:41 AM hudson.util.BootFailure publish
SEVERE: Failed to initialize Jenkins
hudson.util.HudsonFailedToLoad: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.WebAppMain$3.run(WebAppMain.java:250)
Caused by: org.jvnet.hudson.reactor.ReactorException: java.lang.Error: java.lang.reflect.InvocationTargetException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
        at jenkins.InitReactorRunner.run(InitReactorRunner.java:48)
        at jenkins.model.Jenkins.executeReactor(Jenkins.java:1117)
        at jenkins.model.Jenkins.<init>(Jenkins.java:921)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at hudson.model.Hudson.<init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1083)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        ... 8 more
Caused by: io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration: '/var/jenkins_home/casc_configs/jenkins.yaml' isn't a valid path.
        at io.jenkins.plugins.casc.ConfigurationAsCode.configs(ConfigurationAsCode.java:572)
        at io.jenkins.plugins.casc.ConfigurationAsCode.getStandardConfigSources(ConfigurationAsCode.java:285)
        at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:275)
        at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:267)
        ... 13 more

Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins cleanUp
INFO: Stopping Jenkins
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins$18 onAttained
INFO: Started termination
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins$18 onAttained
INFO: Completed termination
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins _cleanUpDisconnectComputers
INFO: Starting node disconnection
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins _cleanUpShutdownPluginManager
INFO: Stopping plugin manager
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins _cleanUpPersistQueue
INFO: Persisting build queue
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins _cleanUpAwaitDisconnects
INFO: Waiting for node disconnection completion
Aug 22, 2019 1:43:42 AM jenkins.model.Jenkins cleanUp
INFO: Jenkins stopped

**Comment by ewelinawilkosz** [comment]
can you try with https://github.com/ewelinawilkosz/praqma-jenkins-casc - jenkins4casc requires update (which will come) and praqma-jenkins-casc has more examples and explanation
